{{- if .Values.abacus.kathy.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "abacus-agent.fullname" . }}-kathy-external-secret
  labels:
    {{- include "abacus-agent.labels" . | nindent 4 }}
  annotations:
    update-on-redeploy: "{{ now }}"
spec:
  secretStoreRef:
    name: {{ include "abacus-agent.cluster-secret-store.name" . }}
    kind: ClusterSecretStore
  refreshInterval: "1h"
  # The secret that will be created
  target:
    name: {{ include "abacus-agent.fullname" . }}-kathy-secret
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "abacus-agent.labels" . | nindent 10 }}
      data:
        {{- range .Values.abacus.kathy.signers }}
        {{- if eq .keyConfig.type "hexKey" }}
        ABC_BASE_SIGNERS_{{ .name | upper }}_KEY: {{ printf "'{{ .%s_signer_key | toString }}'" .name }}
        {{- end }}
        {{- end }}
        {{- if .Values.abacus.kathy.aws }}
        AWS_ACCESS_KEY_ID: {{ print "'{{ .aws_access_key_id | toString }}'" }}
        AWS_SECRET_ACCESS_KEY: {{ print "'{{ .aws_secret_access_key | toString }}'" }}
        {{- end }}
  data:
  {{- range .Values.abacus.kathy.signers }}
  {{- if eq .keyConfig.type "hexKey" }}
  - secretKey: {{ printf "%s_signer_key" .name }}
    remoteRef:
      key: {{ printf "%s-%s-key-kathy" $.Values.abacus.context $.Values.abacus.runEnv }}
      property: privateKey
  {{- end }}
  {{- end }}
  {{- if .Values.abacus.kathy.aws }}
  - secretKey: aws_access_key_id
    remoteRef:
      key: {{ printf "%s-%s-kathy-aws-access-key-id" .Values.abacus.context .Values.abacus.runEnv }}
  - secretKey: aws_secret_access_key
    remoteRef:
      key: {{ printf "%s-%s-kathy-aws-secret-access-key" .Values.abacus.context .Values.abacus.runEnv }}
  {{- end }}
{{- end }}
