{{- if .Values.abacus.validator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "abacus-agent.fullname" . }}-validator
  labels:
    {{- include "abacus-agent.labels" . | nindent 4 }}
data:
{{ $index := 0 }}
{{- range .Values.abacus.validator.configs }}
  validator-{{ $index }}.env: |
{{- include "abacus-agent.config-env-vars" (dict "config" . "agent_name" "validator" "dot_env_format" true) | indent 4 }}
{{ $index = add1 $index }}
{{- end }}
{{- end }}
